import { fromJSON } from "postcss";

export { HomeView } from "./home";
//export { BasicsView } from "./basics";
export { TestView } from "./test";
export { CreateView } from "./create";
export { AuthorityView } from "./authority";
export { BurnView } from "./burn";
export { MoreView } from "./more";
export { UpdataView } from "./updata";
export { MultiSenderView } from "./multiSender"
export { MarketView } from "./market"
export { PoolView } from "./pool"
export { RemoveView } from "./remove"
export { MarketManageView } from "./marketmanage"
export { MintView } from "./mint"
export { FrozenView } from "./frozen"
export { PoolAndBuyView } from "./poolandbuy"
export { TradeBotView } from "./tradebot"
export { MarketManageV2View } from "./marketmanagev2"
export { MarketagePumpView } from "./marketagepump"
export { CreateAndBuyPumpView } from "./createandbuypump"
export { TradeBotPumpView } from "./tradebotpump"
export { MeteoraPoolView } from "./meteora"
export { MeteoraLiqView } from "./meteoraliq"
export { RemoveMeteoraLiqView } from './removemeteoraliq'
export { MeteoraSwapView } from "./meteoraswap"
